Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,65 +1,40 @@
+
 name: Build APK
 
-code
-
 on:
-
-push:
-
-workflow_dispatch:
+  push:
+  workflow_dispatch:
 
 jobs:
+  build:
+    runs-on: ubuntu-latest
 
-build:
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v4
 
-runs-on: ubuntu-latest
+      - name: Set up JDK 17
+        uses: actions/setup-java@v4
+        with:
+          java-version: '17'
+          distribution: 'temurin'
 
-steps:
+      - name: Setup Gradle
+        uses: gradle/actions/setup-gradle@v4
+        with:
+          gradle-version: 8.7
 
-uses: actions/checkout@v4
+      - name: Build APK
+        run: |
+          chmod +x gradlew || true
+          if [ -f ./gradlew ]; then
+            ./gradlew assembleDebug
+          else
+            echo "gradlew not found!" && exit 1
+          fi
 
-name: Set up JDK 17
-
-uses:
-
-actions/setup-java@v4
-
-with:
-
-java-version: '17'
-
-distribution: 'temurin'
-
-name: Setup Gradle
-
-uses:
-
-gradle/actions/setup-gradle@v4
-
-with:
-
-gradle-version: 8.7
-
-name: Build Debug APK
-
-run: |
-
-chmod +x gradlew || true
-
-if [ -f "./gradlew" ]; then ./gradlew assembleDebug
-
-else
-
-fi gradle assembleDebug
-
-name: Upload APK
-
-uses:
-
-actions/upload-artifact@v4
-
-with:
-
-name: ezy tailor
-
-path: app/build/outputs/apk/debug/*.apk
+      - name: Upload APK
+        uses: actions/upload-artifact@v4
+        with:
+          name: LUQMAN-TAILOR-APK
+          path: app/build/outputs/apk/debug/*.apk
